"""initial schema

Revision ID: 8f6a96333820
Revises: 
Create Date: 2026-07-04 14:14:26.506893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6a96333820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_code'), 'universities', ['code'], unique=True)
    op.create_table('majors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('spbstu_internal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_majors_code'), 'majors', ['code'], unique=False)
    op.create_table('applicants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('applicant_code', sa.String(length=50), nullable=False),
    sa.Column('is_bvi', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('exam_score', sa.Integer(), nullable=True),
    sa.Column('achievement_score', sa.Integer(), nullable=True),
    sa.Column('target_achievement_score', sa.Integer(), nullable=True),
    sa.Column('preferential_right', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('has_agreement', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['parse_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicants_applicant_code'), 'applicants', ['applicant_code'], unique=False)
    op.create_index(op.f('ix_applicants_major_id'), 'applicants', ['major_id'], unique=False)
    op.create_index(op.f('ix_applicants_snapshot_id'), 'applicants', ['snapshot_id'], unique=False)
    op.create_table('major_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('places', sa.Integer(), nullable=True),
    sa.Column('applications', sa.Integer(), nullable=True),
    sa.Column('agreements', sa.Integer(), nullable=True),
    sa.Column('list_formed_at', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['parse_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_major_stats_major_id'), 'major_stats', ['major_id'], unique=False)
    op.create_index(op.f('ix_major_stats_snapshot_id'), 'major_stats', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_major_stats_snapshot_id'), table_name='major_stats')
    op.drop_index(op.f('ix_major_stats_major_id'), table_name='major_stats')
    op.drop_table('major_stats')
    op.drop_index(op.f('ix_applicants_snapshot_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_major_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_applicant_code'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_majors_code'), table_name='majors')
    op.drop_table('majors')
    op.drop_index(op.f('ix_universities_code'), table_name='universities')
    op.drop_table('universities')
    op.drop_table('parse_snapshots')
    # ### end Alembic commands ###
